package com.cognixia.jump.jdbc.ems_extension.team2model;

import java.io.Serializable;
/**
 * Employee class for use in the ESM project.
 * @author Alexandre Northouse
 *
 */
public class Employee implements Serializable {
	
	//static variables
	private static final long serialVersionUID = 1L;
	private static int idCounter = 0;
	
	//object variables
	private int id;
	private String firstName, lastName;
	private int salary;
	private String jobTitle;
	private String phoneNumber;
	
	
	//constructors
	/**
	 * The default constructor for the class that provides all the variables needed to create a full Employee object.
	 * <p>
	 * The id is auto-generated by the class to ensure no repeated values.
	 * <p>
	 * @param firstName employee's first name
	 * @param lastName employee's last name
	 * @param salary employee's salary
	 * @param jobTitle employee's job title
	 * @param phoneNumber employee's preferred contact number
	 */
	public Employee(String firstName, String lastName, int salary, String jobTitle, String phoneNumber) {
		super();
		this.id = generateNewId();
		this.firstName = firstName;
		this.lastName = lastName;
		this.salary = salary;
		this.jobTitle = jobTitle;
		this.phoneNumber = phoneNumber;
	}

	/**
	 * The secondary constructor for the class that provides a bare-bones employee object with some default values,
	 * mostly used for potential-hires or other members.
	 * <p>
	 * The id is auto-generated by the class to ensure no repeated values, and the salary is fill with a 0.
	 * <p>
	 * @param firstName employee's first name
	 * @param lastName employee's last name
	 * @param jobTitle employee's job title
	 * @param phoneNumber employee's preferred contact number
	 */
	public Employee(String firstName, String lastName, String jobTitle, String phoneNumber) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.salary = 0;
		this.jobTitle = jobTitle;
		this.phoneNumber = phoneNumber;
	}

	
	
	//class methods
	private int generateNewId() {
		idCounter++;
		return idCounter;
	}
	
	
	
	//getters and setters
	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the idCounter
	 */
	public static int getIdCounter() {
		return idCounter;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * @return the salary
	 */
	public int getSalary() {
		return salary;
	}

	/**
	 * @return the jobTitle
	 */
	public String getJobTitle() {
		return jobTitle;
	}

	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @param salary the salary to set
	 */
	public void setSalary(int salary) {
		this.salary = salary;
	}

	/**
	 * @param jobTitle the jobTitle to set
	 */
	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}


	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Override
	public String toString() {
		return "Employee [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", salary=" + salary
				+ ", jobTitle=" + jobTitle + ", phoneNumber=" + phoneNumber + "]";
	}
}